### ISSUE TITLE
Different Predictions at Different Running

### ISSUE THREAD

**Issue by doctorerre** [Yashraj5122/Stock_Market_Prediction#1]
Not issue at all

Hey Yashraj, really like your project with ML and LSTM inference for 30 days. I only have a doubt, why i get different Predictions when running the code at different times. Lets Say yesterday the modelo said thats AAPL was going to increase and now it says thats going to decrease. I am not expert at this kind of model, do You know any reason why this happens?

**Comment by Yashraj5122** [comment]
Hey doctorerre,
I am glad that you liked my repository. Now onto the question -> 

First of all there are 2 types of algorithm I may like to introduce for this question to be answered : 1. **Deterministic** 2.**Stochastic**

Deterministic Algorithms are that algorithms that does not change the results or outputs for same dataset when run multiple times.This happens because deterministic algorithms use a set of rules and logic to make predictions. Example for this are Linear Regression and Logistic Regression which belongs to supervised learning.

Stochastic Algorithms can have multiple outputs or results for different runtime.This happens because stochastic algorithms use probability and randomness to make predictions. Example for this are all deep learning algorithms like CNN, LSTM, RNN etc.

Now coming back to question, based on your doubt and my explanation, we can conclude that LSTM (algorithm used in repository) is a stochastic algorithm. This happens because the neural network we formed in the project are assigned with different weights and when trained, this weights form results based on randomness. Therefore when model is run multiple times , each time it behaves like a different model.

I hope this answers your question !!
